Fixes redirect issues when deletion happens on CLI
dpc-sdp/tide_core pull request #251
Opened 2021-06-28 03:08 UTC by vincent-gao

2021-06-28 03:33 UTC, anthony-malkoun commented
@sonnykt can you take a look at this for me please. My concern is that it fixes the migration rollback issue but doesn't fix say, tide_demo_content being uninstalled.

2021-06-28 03:37 UTC, vincent-gao commented
> @sonnykt can you take a look at this for me please. My concern is that it fixes the migration rollback issue but doesn't fix say, tide_demo_content being uninstalled.

@anthony-malkoun sorry, I didn't mention it on description. it applies https://www.drupal.org/project/drupal/issues/3065207#comment-13214627 patch which fixes uninstalling tide_demo_content issue.

2021-06-28 03:58 UTC, sonnykt commented
@vincent-gao the event subscriber is only applicable if the site has Migrate module enabled. Not all sites have it. The patch from Drupal core for `forceDelete()` is for Drupal 9 and we are not there yet, I'm not sure what is the impact on other contrib modules as I see it as a core API change.

imho the `predelete()` hook in content_lock module is critically wrong. Applying its patch doesn't really fix. The module is doing the wrong action to stop the entity deletion. I think we should implement a predelete hook that runs  to release the lock before content_lock kicks in.

2021-06-28 04:06 UTC, vincent-gao commented
> @vincent-gao the event subscriber is only applicable if the site has Migrate module enabled. Not all sites have it. The patch from Drupal core for `forceDelete()` is for Drupal 9 and we are not there yet, I'm not sure what is the impact on other contrib modules as I see it as a core API change.
> 
> imho the `predelete()` hook in content_lock module is critically wrong. Applying its patch doesn't really fix. The module is doing the wrong action to stop the entity deletion. I think we should implement a predelete hook that releases the lock before content_lock kicks in.

Oh sorry , I just posted wrong link 
it should be https://www.drupal.org/project/content_lock/issues/2951652#comment-12751913
and ok will do predeletehook way.

2021-06-28 04:13 UTC, sonnykt commented
@vincent-gao see the comment #9 on the issue of content_lock https://www.drupal.org/project/content_lock/issues/2951652#comment-12829088

2021-06-28 04:49 UTC, vincent-gao commented
> @vincent-gao see the comment #9 on the issue of content_lock https://www.drupal.org/project/content_lock/issues/2951652#comment-12829088

Just made a change, please take a look @sonnykt

2021-06-28 04:50 UTC, sonnykt requested changes

2021-06-28 04:50 UTC, sonnykt commented on modules/tide_edit_protection/tide_edit_protection.module
> +function tide_edit_protection_entity_predelete(Drupal\Core\Entity\EntityInterface $entity) {
@vincent-gao please don't use full qualified namespace in parameters.

2021-06-28 04:50 UTC, sonnykt commented on modules/tide_edit_protection/tide_edit_protection.module
> +  if (PHP_SAPI == 'cli') {
the predelete hook of content_lock is totally wrong and it causes more issue upon entity deletion not just via CLI. Hence we should release the lock regardless of the situation.
```php
$lock_service->release($entity_id, LanguageInterface::LANGCODE_NOT_SPECIFIED);
```
Just this line is enough. No need to check for CLI, no need to fetch the lock.

2021-06-28 04:50 UTC, sonnykt commented on modules/tide_edit_protection/tide_edit_protection.module
> +  if (PHP_SAPI == 'cli') {
@vincent-gao just increase module_weight of `content_lock` to a big number (eg. 1000) using an update hook in tide_edit_protection. No need to implement this hook.

2021-06-28 05:31 UTC, sonnykt approved these changes

2021-06-28 05:34 UTC, sonnykt commented on modules/tide_edit_protection/tide_edit_protection.module
> +  \Drupal::service('content_lock')
@vincent-gao imo we should have some comments indicating why we need this hook, probably referencing the Drupal issues.

2021-06-28 05:59 UTC, anthony-malkoun approved these changes
Thank you for feedback @sonnykt. This seems like a much cleaner solution to me now. Approved.

2021-06-28 07:37 UTC, anthony-malkoun commented
The only thought I had is does this make it now possible to delete locked content by an editor? Is this even something to be worried about as I don't think many users have the permission to delete and could probably break the lock anyway.

2021-06-28 08:04 UTC, sonnykt commented
@anthony-malkoun if the purpose of `tide_edit_protection` is to prevent content from being deleted by editors, `content_lock` is not really the right choice. I would expect the logic to be more complex with permissions and site restrictions. If the sole purpose is to prevent concurrent editing, releasing the lock upon deletion should not have any issue.

2021-06-28 08:06 UTC, anthony-malkoun commented
> @anthony-malkoun if the purpose of `tide_edit_protection` is to prevent content from being deleted by editors, `content_lock` is not really the right choice. I would expect the logic to be more complex with permissions and site restrictions. If the sole purpose is to prevent concurrent editing, releasing the lock upon deletion should not have any issue.

Yep, agree. I think it's really only there as a guardrail rather than a hard limit. If you have permissions to delete you have permissions to break the lock anyway.

2021-06-29 00:07 UTC, sonnykt commented
hi @anthony-malkoun @vincent-gao I think we should release this change asap. On env with PERSIST_DB on, during deployment the `drush cim` will uninstall tide_demo_content and it is guaranteed to break.

2021-06-29 00:10 UTC, vincent-gao commented
> hi @anthony-malkoun @vincent-gao I think we should release this change asap. On env with PERSIST_DB on, during deployment the `drush cim` will uninstall tide_demo_content and it is guaranteed to break.

sure @sonnykt , I am about to release it right away.

2021-06-29 00:10 UTC, merged