SDPAP-5913: Addition business fields to CMS user account.
dpc-sdp/tide_core pull request #340
Opened 2022-10-05 07:26 UTC by henrytranvan

2022-10-18 00:20 UTC, MdNadimHossain requested changes
Hi @henrytranvan 
There are few things that needs to be cleaned up. Please have a look and let me know if you have any question. Also as this is a core change and also in the next release it will go with drupal/core 9.4 update, can you please create a test PR in the content-reference site. There is a 9.4 test PR in the reference sit, you can branch out from that and use alias to apply this tide_core PR changes. Let me know if you need more info on that.  This is the reference site 9.4 branch that you can use - https://github.com/dpc-sdp/content-reference-sdp-vic-gov-au/pull/134

2022-10-18 00:20 UTC, MdNadimHossain commented on config/install/user.role.site_admin.yml
> +  - 'view vgso_profile revisions'
please add the permissions that are needed. I can see there are lots of permissions which are only content-vic specific. Just add the permissions needed related to this PR please

2022-10-18 00:20 UTC, MdNadimHossain commented on tide_core.install
> +
please use `\Drupal::entityTypeManager()` to create the storage and field for both of the update hook. there are other examples in this file that you can follow. e.g - https://github.com/dpc-sdp/tide_core/blob/1082c243f94fce61cc242110595db4735169e3f5/tide_core.install#L1397

2022-10-18 00:20 UTC, MdNadimHossain commented on tide_core.install
> +  $config_location = [drupal_get_path('module', 'tide_core') . '/config/install'];
this is deprecated from drupal/core 9.3 - `drupal_get_path('module',`
Please use the following one as from the next release we are updating every project to 9.4 - 
`$config_location = [\Drupal::service('extension.list.module')->getPath`
See this - https://www.drupal.org/node/2940438

2022-10-24 00:37 UTC, MdNadimHossain requested changes
Hi @henrytranvan 
Sorry but few more changes required. Please have a look at the comments and let me know if something does not make sense. Also it will be good to add a behat test so that it does a quick check on the fields in the user form if possible

2022-10-24 00:37 UTC, MdNadimHossain commented on tide_core.install
> +    'field.storage.user.field_notes' => 'field_storage_config',
So you are creating the field storage here, I don't see anything to create the fields though. e.g - `field.field.user.user.field_business_contact_number.yml`
`field.field.user.user.field_business_name.yml`
`field.storage.user.field_business_contact_number.yml`

2022-10-24 00:37 UTC, MdNadimHossain commented on tide_core.install
> +}
Please do not use this `_tide_import_single_config` anymore, I will add a tag in this function to say deprecated
Also you can create the `entity_form_display` and `entity view display` using the `\Drupal::entityTypeManager()` Please check the following example - https://github.com/dpc-sdp/tide_landing_page/blob/develop/tide_landing_page.install#L1328

2022-10-24 00:37 UTC, MdNadimHossain commented on tide_core.install
> +  _tide_import_single_config('user.role.authenticated', $config_location);
I do not think it needs permission for the authenticated user.

2022-10-24 00:37 UTC, MdNadimHossain commented on tide_core.install
> +  _tide_import_single_config('user.role.site_admin', $config_location);
does the site_admin needs all these permissions though ! isn't it like a normal other fields that just shows up and users can input things. I don't think it needs the field level permission. Can you please check if it works without these field level permission and user can input the values.

2022-10-24 00:37 UTC, MdNadimHossain commented on config/install/user.role.site_admin.yml
>    - 'view landing_page revisions'
don't think these permission are needed, please check the comment below.

2022-10-24 00:37 UTC, MdNadimHossain commented on config/install/user.role.authenticated.yml
> +  - 'view published share link token entities'
this one shouldn't require for authenticated users

2022-10-24 00:37 UTC, MdNadimHossain commented on composer.json
> +        "drupal/field_permissions": "^1.2",
this is not needed, it i just normal new fields that getting added in the user form, please check if it works fine without this field level permissions.

2022-10-26 00:03 UTC, MdNadimHossain requested changes
Hey @henrytranvan 
looks good now. But can you please add a behat test to cover different permission scenario.

2022-10-26 23:20 UTC, vincent-gao commented
hey @henrytranvan , could you please add details to the ticket.

2022-11-01 22:42 UTC, MdNadimHossain approved these changes
Looks good to me now, but please do add the details of this PR at the top as Vincent mentioned. e.g related Jira ticket, what changes you are making etc

2022-11-08 04:09 UTC, merged