[SD-188] tide version information
dpc-sdp/tide_core pull request #510
Opened 2024-09-09 11:14 UTC by vincent-gao

### Jira

### Problem/Motivation

### Fix

### Related PRs

### Screenshots

### TODO

2024-09-11 00:23 UTC, vincent-gao commented
The field test failure is not due to this PR, which should be fixed by a separate PR.

2024-09-11 00:27 UTC, tim-yao approved these changes

2024-09-11 00:27 UTC, tim-yao commented on tests/src/Kernel/SystemInfoControllerTest.php
> +    $this->assertEquals($response->getContent(), $cachedResponse->getContent());
Nice test!

2024-09-16 01:51 UTC, GROwen commented
Hey @vincent-gao , I think this is worth refactoring into a sensor that integrates with the [Drupal Monitoring framework](https://www.drupal.org/node/2061153?no_cache=1726450045). We're using it for [a healthz check in bay_monitoring](https://github.com/dpc-sdp/bay_monitoring/blob/main/src/Controller/HealthzController.php) and it would be a major advantage to have these system information features implemented in a consistent way.

The sensor would be defined in tide_core and could use a more specific endpoint for Tide rather than `system-info`.

2024-09-16 03:15 UTC, vincent-gao commented
> Hey @vincent-gao , I think this is worth refactoring into a sensor that integrates with the [Drupal Monitoring framework](https://www.drupal.org/node/2061153?no_cache=1726450045). We're using it for [a healthz check in bay_monitoring](https://github.com/dpc-sdp/bay_monitoring/blob/main/src/Controller/HealthzController.php) and it would be a major advantage to have these system information features implemented in a consistent way.
> 
> The sensor would be defined in tide_core and could use a more specific endpoint for Tide rather than `system-info`.

Hi @GROwen,
I agree that it's a good suggestion. however, there is currently no dependency relationship between the tide_core and bay_monitoring module, which makes integration challenging logically. this is also beyond the current scope of work. I propose we address this in a separate ticket. 
the solution will be to move and refactor this PR into the bay_monitoring module. The URIs will be `healthz/system-info` and `healthz/system-info/fields/{types}`.
what do you think @GROwen ?

cc @tim-yao, by this way, you need the TOKEN to access the results.

2024-09-16 03:32 UTC, tim-yao commented
> > Hey @vincent-gao , I think this is worth refactoring into a sensor that integrates with the [Drupal Monitoring framework](https://www.drupal.org/node/2061153?no_cache=1726450045). We're using it for [a healthz check in bay_monitoring](https://github.com/dpc-sdp/bay_monitoring/blob/main/src/Controller/HealthzController.php) and it would be a major advantage to have these system information features implemented in a consistent way.
> > The sensor would be defined in tide_core and could use a more specific endpoint for Tide rather than `system-info`.
> 
> Hi @GROwen, I agree that it's a good suggestion. however, there is currently no dependency relationship between the tide_core and bay_monitoring module, which makes integration challenging logically. this is also beyond the current scope of work. I propose we address this in a separate ticket. the solution will be to move and refactor this PR into the bay_monitoring module. The URIs will be `healthz/system-info` and `healthz/system-info/fields/{types}` , and a sensor page entry point. what do you think @GROwen ?
> 
> cc @tim-yao, by this way, you need the TOKEN to access the results.

If the token is easy to set up in our GHA ci job, then I am okay with that. @GROwen 
But it makes the tide version api is not accessible for team members, like QA or delivery team if they just want to use API to check the version like Ripple provide in https://www.vic.gov.au/api/tide/

2024-09-16 03:37 UTC, vincent-gao commented
hey @tim-yao If we refactor this in a separate ticket using the sensor approach, team members will be able to access the version information via the `admin/reports/monitoring` page.

2024-09-16 07:37 UTC, anthony-malkoun requested changes
I _really_ like this @vincent-gao! Can I make a request and have Drupal and Drush versions returned as well if you're parsing `composer.json` anyway? I'd love to see PHP version too but might be trickier.

2024-09-16 11:16 UTC, vincent-gao commented on src/Controller/SystemInfoController.php
> +      $this->logger->error('composer.json not found at @path', ['@path' => $composer_file_path]);
hey @anthony-malkoun,
The `composer.lock` file does not include `sdp_version`. I will keep `/api/v1/system-info` endpoint will continue to return:
```
{
    "tideVersion": "dev-reference",
    "sdpVersion": "1.47.0"
}
```

 I have created a new endpoint `api/v1/package-version` to meet your suggestions. This endpoint provides the specific package version along with the PHP version. For more details, please refer to the examples in the PR description.
cc @tim-yao

2024-09-17 00:37 UTC, tim-yao commented on src/Controller/SystemInfoController.php
> +      $this->logger->error('composer.json not found at @path', ['@path' => $composer_file_path]);
Hi @vincent-gao @anthony-malkoun as discussed, I suggest to remove `sdpVersion` now as it's not making sense anymore if we move towards to the new release process

2024-09-17 07:24 UTC, anthony-malkoun commented
> > Hey @vincent-gao , I think this is worth refactoring into a sensor that integrates with the [Drupal Monitoring framework](https://www.drupal.org/node/2061153?no_cache=1726450045). We're using it for [a healthz check in bay_monitoring](https://github.com/dpc-sdp/bay_monitoring/blob/main/src/Controller/HealthzController.php) and it would be a major advantage to have these system information features implemented in a consistent way.
> > The sensor would be defined in tide_core and could use a more specific endpoint for Tide rather than `system-info`.
> 
> Hi @GROwen, I agree that it's a good suggestion. however, there is currently no dependency relationship between the tide_core and bay_monitoring module, which makes integration challenging logically. this is also beyond the current scope of work. I propose we address this in a separate ticket. the solution will be to move and refactor this PR into the bay_monitoring module. The URIs will be `healthz/system-info` and `healthz/system-info/fields/{types}` , and a sensor page entry point. what do you think @GROwen ?
> 
> cc @tim-yao, by this way, you need the TOKEN to access the results.

@GROwen / @vincent-gao continuing this conversation, I think using the monitoring approach doesn't necessarily need a relationship between `tide_core` and `bay_monitoring`? I also think looking at Guy's example, you can still have your own endpoint without a token required if that's what you define in your routing?

Guy, the bit I'm trying to get my head around is are you thinking a custom "sensor" that would return the date required? Doesn't the sensor need to return some sort of "status"?

2024-09-17 08:12 UTC, anthony-malkoun commented
> > > Hey @vincent-gao , I think this is worth refactoring into a sensor that integrates with the [Drupal Monitoring framework](https://www.drupal.org/node/2061153?no_cache=1726450045). We're using it for [a healthz check in bay_monitoring](https://github.com/dpc-sdp/bay_monitoring/blob/main/src/Controller/HealthzController.php) and it would be a major advantage to have these system information features implemented in a consistent way.
> > > The sensor would be defined in tide_core and could use a more specific endpoint for Tide rather than `system-info`.
> > 
> > 
> > Hi @GROwen, I agree that it's a good suggestion. however, there is currently no dependency relationship between the tide_core and bay_monitoring module, which makes integration challenging logically. this is also beyond the current scope of work. I propose we address this in a separate ticket. the solution will be to move and refactor this PR into the bay_monitoring module. The URIs will be `healthz/system-info` and `healthz/system-info/fields/{types}` , and a sensor page entry point. what do you think @GROwen ?
> > cc @tim-yao, by this way, you need the TOKEN to access the results.
> 
> @GROwen / @vincent-gao continuing this conversation, I think using the monitoring approach doesn't necessarily need a relationship between `tide_core` and `bay_monitoring`? I also think looking at Guy's example, you can still have your own endpoint without a token required if that's what you define in your routing?
> 
> Guy, the bit I'm trying to get my head around is are you thinking a custom "sensor" that would return the date required? Doesn't the sensor need to return some sort of "status"?

I've done a bit of research on `monitoring` and I think what @GROwen is saying (correct me if I'm wrong Guy!) is that you can still do this in `tide_core` with no dependency on `bay_monitoring` but if you use the Monitoring framework it can be something that appears in e.g. in https://develop.content.vic.gov.au/admin/reports/monitoring. An example is you could have a sensor (there might be one already) that returns PHP version and reports a fail status if it's less than our trigger value. All the example Guy gives in `bay_monitoring` does is wrap the sensors in a route to expose them outside of UI. @vincent-gao if easier maybe let's talk about this and we can grab Guy as well. 

An example of one that might be close to what you need is https://develop.content.vic.gov.au/admin/reports/monitoring/sensors/user_sessions_authenticated which has unaggregated output, that is multiple values of output and no threshold, that is it always returns "OK". Then your route will simply execute that sensor.

2024-09-17 22:49 UTC, GROwen commented
That nails it perfectly @anthony-malkoun 
![keanu-thanks](https://github.com/user-attachments/assets/d6fad281-b36c-4d54-8648-6f4e6fa45d86)

2024-09-18 23:29 UTC, vincent-gao commented
@anthony-malkoun @GROwen 
Thank you for the replies . I will add `monitoring` module as a dependency to `tide_core` and refactor the code to adapt this method.

2024-09-23 00:21 UTC, vincent-gao commented
hey @anthony-malkoun 

things have been made to meet CR feedbacks

1. the `monitoring` module has been added as a dependency for the `tide_core` module, ensuring sensor interactions are functional.
2.  the sensor is the only place for generating the main package information, all other components will consume this data, which makes the format and the content consistent. 
 ```json
{
    "package_versions": {
        "drupal/core": "10.3.5",
        "dpc-sdp/tide": "dev-mono-repo-test",
        "dpc-sdp/tide_core": "dev-feature/SD-268-mono-repo-phase-1",
        "drush/drush": "12.5.3",
        "php": "8.3.10"
    }
}
 ```
![CleanShot 2024-09-23 at 10 17 19](https://github.com/user-attachments/assets/7be18e26-a46a-451d-9bad-45913097d78c)
3. update the URLS
4. update tests.

2024-09-24 07:26 UTC, MdNadimHossain approved these changes
@vincent-gao As I can see the PR already been reviewed by others, so good to inform them as the CR changes has been done. Looks good to me, I have some minor validation and improvement suggestions. Good if we can add them else it does not really harm at this point. UP to you .

2024-09-24 07:26 UTC, MdNadimHossain commented on src/Plugin/monitoring/SensorPlugin/TidetimesSensorPlugin.php
> +        {% for section, data in sections %}
Provide a more robust fallback mechanism in case some data is missing: 
```suggestion
        {% for section, data in sections ?? {} %}
```

2024-09-24 07:26 UTC, MdNadimHossain commented on src/Plugin/monitoring/SensorPlugin/TidetimesSensorPlugin.php
> +      </style>
Not necessary to do it now, but in future if this grows may be we can separate it in twig template and also separate the style and load it as library for better readability.

2024-09-25 00:18 UTC, merged