Feature/sd 345 quick exit
dpc-sdp/tide_core pull request #524
Opened 2024-10-16 03:59 UTC by sharmasahil

### SD-345

### Implement site specific quick exit button field in sites taxonomy.

### Fix

### No Related PRs

### Screenshots

### TODO

2024-10-16 04:56 UTC, vincent-gao commented
hey @sharmasahil , 
thanks for the changes.
but please update the PR title to follow the format below and ensure it’s clear and meaningful.
e.g. `[SD-345] Add Site-Specific “Quick Exit” Button Field to Sites Taxonomy`

details of the PR
```
### Jira
https://digital-vic.atlassian.net/browse/SD-345

### Changes
.........

```

2024-10-16 04:57 UTC, vincent-gao requested changes
hey @sharmasahil please see my comments.

2024-10-16 05:08 UTC, sharmasahil commented
> hey @sharmasahil , thanks for the changes. but please update the PR title to follow the format below and ensure it’s clear and meaningful. e.g. `[SD-345] Add Site-Specific “Quick Exit” Button Field to Sites Taxonomy`
> 
> details of the PR
> 
> ```
> ### Jira
> https://digital-vic.atlassian.net/browse/SD-345
> 
> ### Changes
> .........
> ```

Done

2024-10-16 09:33 UTC, vincent-gao commented
@sharmasahil the title~ 
![CleanShot 2024-10-16 at 20 32 24](https://github.com/user-attachments/assets/3f628970-84b0-43dc-9e9b-9f5eb2b37427)
change it from `Feature/sd 345 quick exit` to `[SD-345] Implement Ability to Remove Quick Exit from Specific Site Sections`
I have changed it for you.

2024-10-16 09:51 UTC, vincent-gao commented
hey @sharmasahil some issues,
1. The tests have failed. Please review the details here https://github.com/dpc-sdp/tide_core/actions/runs/11360325150/job/31597880122?pr=524 .
   - https://github.com/dpc-sdp/dev-tools/blob/master/.ahoy.yml#L165 may help.
2. Please try to install the tide_core module locally and then enable the tide_site module. Once installed, run the behat tests for both tide_site and tide_core. For more details on setting up and running tests, refer to the [development and maintenance guide](https://github.com/dpc-sdp/tide_core/blob/develop/README.md#development-and-maintenance).
    - The reason I’m requesting this is that we currently don’t have a way to automate testing for submodules. To be safe, please perform manual testing for now. The issue with automating these tests will be addressed in a future sprint.

2024-10-18 02:21 UTC, sharmasahil commented
> hey @sharmasahil some issues,
> 
> 1. The tests have failed. Please review the details here https://github.com/dpc-sdp/tide_core/actions/runs/11360325150/job/31597880122?pr=524 .
>    
>    * https://github.com/dpc-sdp/dev-tools/blob/master/.ahoy.yml#L165 may help.
> 2. Please try to install the tide_core module locally and then enable the tide_site module. Once installed, run the behat tests for both tide_site and tide_core. For more details on setting up and running tests, refer to the [development and maintenance guide](https://github.com/dpc-sdp/tide_core/blob/develop/README.md#development-and-maintenance).
>    
>    * The reason I’m requesting this is that we currently don’t have a way to automate testing for submodules. To be safe, please perform manual testing for now. The issue with automating these tests will be addressed in a future sprint.

This is fixed Vincent and also behat test require fix as discussed.

2024-10-18 03:12 UTC, MdNadimHossain requested changes
@seanhamlin thanks for making the changes. The only thing I am requesting is changing the var name in js for the parent field. Have a look. Thanks

2024-10-18 03:12 UTC, MdNadimHossain commented on modules/tide_site/js/quick_exit.js
> +        var parent = ($('.taxonomy-term-sites-form  #edit-parent'));
Instead of using parent, which is a common jQuery method, use a more descriptive variable name like parentField to avoid confusion.

2024-10-18 03:44 UTC, sharmasahil commented
> @seanhamlin thanks for making the changes. The only thing I am requesting is changing the var name in js for the parent field. Have a look. Thanks

@MdNadimHossain This is fixed Nadim, Thanks!!

2024-10-21 05:32 UTC, vincent-gao commented
hey @sharmasahil could you please fix the linting issues, more details https://github.com/dpc-sdp/tide_core/actions/runs/11397035111/job/31711837299?pr=524

2024-11-26 01:58 UTC, merged