Ckedito5 patch for table cell resize
dpc-sdp/tide_core pull request #533
Opened 2024-10-31 05:18 UTC by sharmasahil

### Jira

[SD-358] - Control WYSIWYG and data table column widths in ckeditor

### Fix

Applied patch to enable table cell width control.

2024-11-01 03:25 UTC, vincent-gao requested changes
hey @sharmasahil 
do you need an update hook to apply the changes across all sites?
Also, could you clarify the need for a local patch?

2024-11-14 23:17 UTC, sharmasahil commented
> hey @sharmasahil do you need an update hook to apply the changes across all sites? Also, could you clarify the need for a local patch?

Thanks for the review @vincent-gao, I have updated the PR with comments and also removed local patch, put install hook too.

2024-11-18 03:50 UTC, vincent-gao approved these changes
hey @sharmasahil 
Just a few minor things, and it's perfectly fine if you don't want to make any changes.

2024-11-18 03:50 UTC, vincent-gao commented on modules/tide_landing_page/src/Plugin/jsonapi/FieldEnhancer/BasicTextEnhancer.php
> +      foreach ($processedDom->getElementsByTagName('body')->item(0)->childNodes as $node) {
can this be simplified by using `DOMDocument::saveHTML` directly on the <body> element.
e.g.  
```php
$processedBodyContent = $processedDom->saveHTML($processedDom->getElementsByTagName('body')->item(0));
```

2024-11-18 03:50 UTC, vincent-gao commented on modules/tide_landing_page/src/Plugin/jsonapi/FieldEnhancer/BasicTextEnhancer.php
> +      libxml_clear_errors();
👍

2024-11-18 03:50 UTC, vincent-gao commented on modules/tide_ckeditor/modules/ckeditor_tablecol_resize/js/ckeditor5_plugins/tableColResize/src/tablecolresizeediting.js
> +        console.log('col upcast', colWidth);
the console.log statement should be removed or replaced with a proper logging mechanism if needed for debugging.

2024-11-25 03:02 UTC, merged