Settings for media alias display for documents type
dpc-sdp/tide_core pull request #557
Opened 2024-11-27 03:35 UTC by sharmasahil

### Jira
https://digital-vic.atlassian.net/browse/SD-518
### Problem/Motivation
Media library - allow alias for media items
### Fix
Integrated new media file alias module with only document file type enabled.
### Related PRs

### Screenshots

### TODO

2024-11-28 04:42 UTC, vincent-gao requested changes
hey @sharmasahil, please take a look into my comments.

2024-11-28 04:42 UTC, vincent-gao commented on config/install/media_alias_display.settings.yml
> +_core:
This configuration cannot reside here and you don't need it, as it is defined by another module and cannot be imported.

2024-11-28 05:19 UTC, vincent-gao approved these changes
Thanks @sharmasahil . It looks like a simple change. ✅

2024-11-28 05:19 UTC, vincent-gao commented
ready for test

2024-11-28 05:41 UTC, sharmasahil commented
> ready for test

Thanks for the approval @vincent-gao, moved it to QA, we need to still review the media_library dependency for this new module before we merge it.

2024-11-28 22:08 UTC, vincent-gao commented
hey @sharmasahil , could you please fix the failed build

2024-11-29 01:27 UTC, sharmasahil commented
> hey @sharmasahil , could you please fix the failed build

Fixed the build.

2024-12-13 00:12 UTC, sharmasahil commented
> hey @sharmasahil , could you please fix the failed build

@vincent-gao Please review the lastest commit from today for the autopublish of draft media on node publish.

2024-12-16 01:44 UTC, vincent-gao approved these changes
LGTM, @sharmasahil 
ready for testing.

2024-12-24 02:50 UTC, merged